---
title: Java 异常处理
categories:
- Software
- Backend
- Java
- JavaSE
- 异常处理
---
# Java 异常处理

进行异常处理必须使用try程序块,将可能产生异常的放在try中,当JVM执行过程中发现了异常,会立即停止执行后续代码,然后开始查找异常处理器,对try后面的catch块按次序进行匹配检查,一旦找到一个匹配者,则执行catch块中的代码,不再检查后面的catch块,如果try块中没有异常发生,则程序执行过程中将忽略后面的catch块

以下为异常处理语句格式:

```java
try{
    语句块;
}
catch(异常类名 参变量名){
    语句块;
}
finally{
    语句块;
}
```

**说明**

- try语句块用来启动Java的异常处理机制,一个try可以引导多个catch块
- 异常发生后,try块中的剩余语句将不再执行
- 异常对象是依靠以catch语句为标志的异常处理语句块来捕捉和处理的,catch部分的语句块中的代码执行的条件是,首先在try块中发生了异常,其次是异常的类型与catch要捕捉的一致,在此情况下,运行系统会将异常对象传递给catch中的参变量,在catch块中可以通过该对象获取异常的具体信息
- 在该结构中,可以无finally部分,但如果存在,则无论异常发生否,finally部分的语句均要执行,即便是try或catch块中含有退出方法的语句return,也不能阻止finally代码块的执行,在进行方法返回前要先执行finally块,除非执行中遇到`System.exit(0)`将停止程序运行,这种情形不会执行finally块

多异常处理是通过在一个try块后面定义若干个catch块来实现的,每个catch块用来接收和处理一种特定的异常对象,每个catch块有一个异常类名作为参数,一个异常对象能否被一个catch语句块所接受,主要看该异常对象与catch块的异常参数的匹配情况

**[例9-2]**根据命令行输入的元素位置值查找数组元素的值

```java
public class Ex9_2{
    public static void main(String[] args) {
        int arr[]={100,200,300,400,500,600};
        try{
            int index1 = Integer.parseInt(args[0]);
            System.out.println("元素值为:"+arr[index1]);
        }catch (ArrayIndexOutOfBoundsException a){
            System.out.println("数组下标出界");
        }catch (NumberFormatException n){
            System.out.println("请输入一个整数");
        }finally {
            System.out.println("运行结束");
        }
    }
}
```

程序运行时,要从命令行输入一个参数,这时根据用户的输入存在各种情况

- 如果输入的数值是0~5之间的整数,将输出显示相应数组元素的值
- 如果输入的数据不是整数,则在执行`Integer.parseInt(args[0]);`时产生NumberFormatException异常,程序中捕获到该异常后,提示用户"请输入一个整数"
- 两种情形将出现ArrayIndexOutOfBoundsException异常,一种是用户未输入命令行参数,另一种是用户输入序号超出数组范围,程序中捕获到该类异常后,显示"数组下标出界"
- 无论异常是否发生,程序最后要执行第12行finally块的内容

同一个try对应有多个catch块,还要注意catch的排列次序,以下排列将不能通过编译,原因在于Exception是ArithmeticException的父类,父类包含子类范畴,如果发生算术异常,第一个catch块中已经可以捕获,所以第二个catch将无意义

```java
try{
    int x =4/0;
    System.out.println("come here?");
}catch(Exception e){
    System.out.println("异常!"+e.toString());
}catch (ArithmeticException e){
    System.out.println("算术运行异常! "+e.toString());
}
```

如果将两个catch块颠倒,则编译就可以通过,但运行发生ArithmeticException异常时,遇到一个成功匹配的catch块,以后的catch块不再进行匹配检查